name: CI/CD – React.js Application with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-test-push:
    name: Build, Test and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code from the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Cache Docker build layers to improve performance
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. Extract repository name (e.g., user/repo → repo)
      - name: Extract repository name
        id: repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"

      # 5. Extract short commit SHA (first 7 characters)
      - name: Extract short SHA
        id: short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # 6. Build Docker image using the development Dockerfile (includes Node/npm)
      - name: Build Docker image for tests
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile.dev
          tags: ${{ steps.repo.outputs.REPO_NAME }}-dev:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # 7. Run application tests inside the dev Docker container
      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            --workdir /app \
            --entrypoint "" \
            ${{ steps.repo.outputs.REPO_NAME }}-dev:latest \
            sh -c "npm install && npm run test --reporter=verbose"
        env:
          CI: true
          NODE_ENV: test
        timeout-minutes: 3

      # 8. Authenticate to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 9. Build and push the production image to Docker Hub (Nginx serving dist)
      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          target: prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROJECT_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROJECT_NAME }}:${{ steps.short_sha.outputs.SHORT_SHA }}
